- Implementation/[BOJ]16927.py
- Implementation/[BOJ]21608.py
21608_상어 초등학교, 16927_배열 돌리기 꼭 다시 풀어보기!
> 순수연 / 구현 / 23.03.31 / 좀 더 라이브러리에 대해 익숙해지자!

- BruteForce/BFS & DFS/0511/[백준] 1012_유기농 배추.py
- BruteForce/BFS & DFS/0511/[백준] 16956_늑대와 양.py
- BruteForce/BFS & DFS/0511/[백준] 17086_아기 상어2.py
- BruteForce/BFS & DFS/0511/[백준] 2667_단지번호붙이기.py
- BruteForce/BFS & DFS/0511/[백준] 4963_섬의 개수.py
- BruteForce/BFS & DFS/0511/[백준] 7562_나이트의 이동.py
> BFS/DFS : [#51][#52][#53][#54][#55][#56] 최재훈 - 모든 문제를 bfs로만 푸는 습관이 있는데 dfs도 배워야겠다.

- BFS DFS/0511/[BOJ]1012_유기농배추.py
- BFS DFS/0511/[BOJ]17086_아기상어2.py
- BFS DFS/0511/[BOJ]2667_단지번호붙이기.py
- BFS DFS/0511/[BOJ]4963_섬의개수.py
- BFS DFS/0511/[BOJ]7562_나이트의이동.py
[못 푼 문제]
[#51] 늑대와 양
[80% 푼 문제]
[#54] 아기상어2
[푼 문제]
나머지 문제들
비슷한 유형의 문제라면 응용은 잘 하는 것 같다!
하지만 처음 보는 문제라면 아직 BFS/DFS 관련해서 못 푸는 것 같다.
좀 더 많은 문제를 풀어봐서 유형에 익숙해져야겠다.
> BFS/DFS : [#52][#53][#54][#55][#56] 순수연 - BFS 관련 문제를 풀어봐야겠다.

- BruteForce/BFS & DFS/0511/[백준] 1012_유기농 배추.py
- BruteForce/BFS & DFS/0511/[백준] 4963_섬의 개수.py
- BruteForce/BFS & DFS/0514/[백준] 13023_ABCDE.py
- BruteForce/BFS & DFS/0514/[백준] 17836_공주님을 구해라!.py
- BruteForce/BFS & DFS/0514/[백준] 18513_샘터.py
- BruteForce/BFS & DFS/0514/[백준] 2636_치즈.py
- #67 : 이 문제는 백트래킹이랑 dfs를 알아야 풀 수 있었다. 계속 미뤄왔던 개념들이었는데 이번에 이 문제를 풀면서 공부하게 되었다. 백트래킹을 완전 이해한 건 아니지만 이제 조금 이해는 한 것 같다. 비록 이 문제를 스스로 풀지는 못했지만, 이 문제가 백트래킹의 이해를 높이는데 도움을 준 것 같다.
- #68 : 반례를 생각하는 과정이 너무 어렵다. 어떻게든 풀긴 한 것 같지만 풀이가 깔끔한 것 같지는 않아서 최적화코드를 생각해봐야겠다.
- #69 : 처음 봤을 때 못 풀 줄 알았다. 어디서부터 bfs를 돌려야 할 지 감이 안 왔다. 그래도 고민하다가 깨닫게 됐고 풀긴했지만, 아직 논리력이 부족하다는 느낌이 든다. 풀고나서도 뭔가 확신이 제대로 안 들었다. 경험이 해결해주리라 믿겠다
- #70 : 배열을 이용해서 풀었는데 다른사람들 풀이에 비해 시간이 너무 오래걸렸다. 배열을 사용하면 그 샘터와 집이 존재할 수있는 길이만큼 배열의 길이를 만들어줘야돼서 그런 것 같다. 이중배열을 이용해서 4방향으로 탐색하는 bfs문제만 많이 풀어서 bfs는 배열로 풀어야한다고 고정관념이 생긴 것 같다. 고정관념 버리기!
> BFS/DFS : [#67][#68][#69][#70] 최재훈 - dfs,백트래킹을 좀 알게 되었다, 논리력을 더키워야겠다.

- BFS DFS/0514/[BOJ]13023_ABCDE.py
- BFS DFS/0514/[BOJ]17836_공주님을구해라.py
- BFS DFS/0514/[BOJ]18513_샘터.py
- BFS DFS/0514/[BOJ]2636_치즈.py
골드 문제에 들어와서 하나도 풀지 못했다..
실버 문제부터 다른 유형들을 많이 풀어보고 골드에 도전해야겠다
이번에 푼 골드 문제들도 꼭 다시 풀어볼것!!!
> BFS/DFS : [#67][#68][#69][#70] 순수연 - 골드 문제들은 다 풀지 못했다.. bfs와 dfs에 익숙해진줄 알았는데 아닌가보다.. 더 공부해야겠다!

- dynamic_programming/백준_1106_호텔.py
- dynamic_programming/백준_14722_우유-도시.py
- dynamic_programming/백준_1633_최고의-팀-만들기.py
- dynamic_programming/백준_2565_전깃줄.py
모든 문제 실패
- 이번에는 단 한문제도 풀지 못했다. 원래 commit과 pr 메시지에 푼 이슈 번호로 적었는데, 단 한문제도 맞은게 없어서 빈칸.. 당황스럽다..
- 사실, DP의 개념을 정확히 모르는게 아닐까? 하는 생각이 들었다. 문제를 풀면 풀수록 단순히 DP는 점화식을 구현하는 것이 아니라는걸 깨달았기 때문이다. 큰 문제를 작은 문제로 쪼개는 것이 DP라는데, 그 '작은 문제'를 찾는게 너무 어렵다. 실버도 어려웠지만 어찌어찌 풀었는데, 골드는 진짜..너무..너무 어렵다.. DP 는 아직 골드를 풀때가 아니라 실버를 풀어야하나보다ㅠ
- #100, #99
예제와 반례는 모두 맞았으나 실패하는 경우. 히든케이스를 못 찾았다..
- #101
예제부터 틀리는데, 왜인지 진짜 모르겠다.
- #102
top-down에서 보통 dp의 처음값들은 미리 세팅해놓았는데, 이번에는 `dp[0][0]`이 0이 되는 경우가 생겼다. 그래서 재귀 깊이가 너무 깊어지고, 시간초과. 어떻게 해결해야할까?
> DP : [ ] 마주연 - dp 개념을 다시 공부해야겠다. 반례를 찾자.

- DP/0528/[BOJ]1633_최고의팀만들기.py
- DP/0528/[BOJ]2565_전깃줄.py
문제 이해 + 점화식을 어떻게 세워야할지 감도 잡히지 않았다..ㅠㅠ
그나마 도전했던 문제들은 풀지는 못하고 찾아보았다.
- #99 
- #101
나중에 다시 도전해보고 싶은 문제들..ㅠㅠ..
- #100 
- #102
> DP : 순수연 - 골드보단 실버를 많이 풀고 익숙해지는 노력이 필요한 것 같다..

- Greedy/[BOJ]1080_행렬.py
- Greedy/[BOJ]13305_주유소.py
- Greedy/[BOJ]16953_A→B.py
- Greedy/[BOJ]17615_볼모으기.py
- Greedy/[BOJ]20365_블로그2.py
- Greedy/[BOJ]21314_민겸수.py
아직 구현 능력이 부족한 것 같다
=> 특히 문자열, 배열에 약한 모습이 있는 것 같다
- #113 : 명확한 규칙을 찾지 못했다.
- #114 : 배열이라 어떻게 구현할지에서 애를 먹었다.
- #115 : 규칙 중 일부만 찾아서 통과하지 못했다.
명확한 규칙을 찾고 구현해나가는 습관을 들이자!
> Greedy : [#110][#111][#112] 순수연 - 좀 더 명확한 규칙을 찾기 위해 노력하기!

- PGS/0608/[PGS] [1차] 뉴스 클러스터링.py
- PGS/0608/[PGS] [3차] 압축.py
- PGS/0608/[PGS] 빛의 경로 싸이클.py
- PGS/0608/[PGS] 오픈채팅방.py
- PGS/0608/[PGS] 전화번호 목록.py
- PGS/0608/[PGS] 하노이탑.py
- #126 : 재귀의 교과서라고 불리는 문제이다. 그런데 못풀었다 작정하고 재귀로 풀어야하는 문제에서는 아직 재귀적인 사고가 부족한 것 같다. 그래도 이 문제를 분석하면서 좀 더 이해도가 깊어진 것 같긴 하다. 
- #128 : 이 문제는 Lv2에서 정답률이 가장 낮은 문제이다.  처음엔 시간복잡도에 대한 의심때문에 dfs를 시도하지 않았는데 시도했다고 하더라도 풀 수 있었을지는 모르겠다. 아직 이렇게 완탐,시뮬레이션으로 푸는 풀이도 부족함이 많이 느껴진다
- #129 : 좋은 방법을 찾아 보려다가 못찾고 그냥 풀었다. 풀면서 lsalpha는 검색해보았다. 이런 메서드들은 다외워야 하는걸까?...
그리고 다른 풀이들도 확인해봤는데 Counter에서는 집합연산이 가능함을 알았고, 사고의 확장을 도와주는 풀이도 보았다.
> PGS : [#127][#129][#130][#131] 최재훈 - 메서드들을 기억하자

- 프로그래머스 풀이/프로그래머스_k진수에서-소수-개수-구하기.py
- 프로그래머스 풀이/프로그래머스_거리두기-확인하기.py
- 프로그래머스 풀이/프로그래머스_귤-고르기.py
- 프로그래머스 풀이/프로그래머스_순위-검색.py
- 프로그래머스 풀이/프로그래머스_이모티콘-할인행사.py
- 프로그래머스 풀이/프로그래머스_행렬-테두리-회전하기.py
단순히 배열을 전부 탐색하기에는, 너무 시간이 오래 걸릴거 같았다. 그래서 딕셔너리를 쓰려고 했는데..이건 또 너무 복잡하다. 특히 문자열로 주어져서..
순열을 이용해서 모든 이모티콘에 할인율을 적용해봤는데, 역시나 시간초과. 그런데..어떻게 더 시간을 줄일지 모르겠다.
역시 카카오는 어렵다. 이게 레벨 2..?
문제를 푼다고 해도, 시간초과에서 걸리면 말짱 꽝이다. 시간초과를 항상 생각하고 문제를 풀어야겠다. 그러려면 역시 문제를 보고 어떤 유형인지 판단 할 줄 알아야하고, 그 유형에 맞춰 구현하는 연습을 더 해야겠다. 지금은 문제를 보고 바로 유형 분류가 안되니까 헤매게 된다..
- #142: 무난
- #143: n을 k진수로 바꾸는 방법이 또 없을까? 이렇게 몫과 나머지를 갱신하며 일일히 구하는게 맞나..?
- #144: 처음 푼 코드는 성공하긴 했지만, 너무 지저분하다.
- #145: 인덱스에서 오타 및 실수를 내서, 그걸 찾느라 매우 긴 시간을 소모했다.
> PSG : [#142][#143][#144][#145] 마주연 - 시간초과를 생각하고 구현하자

- PGS/0611/[PGS] 자물쇠와 열쇠.py
- PGS/0615/[PGS] k진수에서 소수 개수 구하기.py
- PGS/0615/[PGS] 귤 고르기.py
- PGS/0615/[PGS] 행렬 테두리 회전하기.py
- PGS/0615/[PGS]거리두기 확인하기.py
- #142 : Counter를 잘 활용해서 풀고 싶었는데 기억이 잘 안났다. 유용한 메서드를 기억하자
- #143 : 멘탈이 나가기 시작한 첫 번째 문제이다. 시간초과가 나서 에라토스테네스의 체를 사용했는데 자꾸 런타임 에러가 났다.
무슨 짓을 해도 안되길래 답을 확인해보니 약수 원리에 의해 루트만큼만 확인하면 됐었다. 이 방법을 알고는 있었고 시간이 절약된다는 건 알았지만 n^2에서 n이 되는 것처럼 드라마틱하게 줄어드는게 아니라고 생각해서 잊고 있었는데 이렇게 당했다...
편식하지말자!
- #144 : 익숙한 문제라서 느낌만 파악하고 바로 풀다가 좀 오래 걸렸다. 겸손하게 모든 문제에 대해 전략을 다 짜고 풀자
- #145 : 멘탈 박살에 박차를 가한 문제이다. 아이디어는 바로 떠올라서 풀었는데 인덱스 문제와 배열에 대한 순간적인 오개념이 있어서 오래 걸렸다. 답을 봤는데 똑같은 아이디어라서 다시 차근차근 풀었더니 됐다
- #146 :  해시와 이분탐색을 활용하는 것 같은데 순간 이분탐색을 어떻게 활용하지라는 생각(그냥 하면되는데..)과 멘탈문제로 풀다가 포기했다.
- #147 : 멘탈박살로 내용이 머릿속에 안들어와서 포기했다.
k진수와 행렬에 의해 멘탈이 박살나서 이틀 공부를 망친 것 같다. 쉽다고 생각한 문제에서 고전해서 너무 심적으로 힘들었다.
이모티콘 문제는 멘탈의 영향도 있겠지만 유형이 바로 보이지 않아서 그냥 포기했다..
나중에 다시 풀어봐야겠다.
> PSG : [#142][#144] 최재훈 - 멘탈 관리하자

- Programmers/0615/[PGS]k진수에서 소수 개수 구하기.py
- Programmers/0615/[PGS]거리두기 확인하기.py
- Programmers/0615/[PGS]귤 고르기.py
- Programmers/0615/[PGS]순위 검색.py
- Programmers/0615/[PGS]이모티콘 할인행사.py
- Programmers/0615/[PGS]행렬 테두리 회전하기.py
지문 파악 잘하기..!
앞으로 지문에서 중요한 부분은 코드에 따로 정리를 해놓고 풀어야겠다.
- #142 
- #143 
- #145
- #144, #147 : bfs/dfs 문제에 대해서 약하다고 느꼈다. 하지만 카카오 문제로 보니 확실히 dfs/bfs 유형이 많이 등장하는 것 같다. 공부를 많이 해야할 것 같다.
- #146 : 효율성을 통과하지 못했다. 시간복잡도를 잘 고려해야 하는 문제였다.
> PSG : [#142][#143][#145] 순수연 - bfs/dfs 공부하기

- programmers/0618/k진수에서소수개수구하기.py
- programmers/0618/거리두기확인하기.py
- programmers/0618/귤고르기.py
- programmers/0618/다단계칫솔판매.py
- programmers/0618/미로탈출명령어.py
- programmers/0618/보석쇼핑.py
- programmers/0618/순위검색.py
- programmers/0618/이모티콘할인행사.py
- programmers/0618/파괴되지않은건물.py
- programmers/0618/행렬테두리회전하기.py
전 것 pr을 머지하지 못해서 합쳐지게 됐습니다.. 이번 것은 한번에 하겠습니다
> PSG : [#142][#143][#144][#145][#146][#147][#148][#149][#150] 유지원 - 그리디에 대해서 다시 차근차근 풀어봐야겠다.. /lv3으로 넘어가니까 감조차 잡지 못하는 것 같다. 조금 더 생각해보기

- Programmers/0622/[PGS] H-Index.py
- Programmers/0622/[PGS] 게임 맵 최단거리.py
- Programmers/0622/[PGS] 멀쩡한 사각형.py
- Programmers/0622/[PGS] 조이스틱.py
- Programmers/0622/[PGS] 주식가격.py
- Programmers/0622/[PGS] 후보키.py
- #158 : 완전 탐색으로 구현해본 문제.. 근데 유형은 그리디라고 되어있었다.. 그리디적인 부분이 있었나?!싶었던 문제..
- #160 :  스택/큐를 활용하는 문제였지만 그냥 배열로 풀었는데도 풀어지기는 했다. 하지만 스택/큐를 활용했다면 시간이 더 빨랐을 것이라 아쉬운 문제
- #161 : 이중 for문을 활용했는데 그냥 for문 하나로도 해결할 수 있는 문제였다 이것도 그래서 아쉬운 것 같다 => 최대한 효율적인 코드를 생각해보자!
- #162 : 정석적인 bfs 문제라 금방 풀 수 있었다! 하지만 코드를 꼼꼼하게 보지 못해서 처음에 틀렸었다..ㅜㅜ 코드를 꼼꼼하게 확인하자!
- #157 : 패턴을 찾는 것에서 실패했다 => 알고보니 최대 공약수를 활용하는 수학?! 문제 같았다.. 이런 문제를 마주치면 어떻게 해야할까..
- #159 : 예외적인 케이스들을 생각하지 못해서 실패했다. => 예외적인 케이스들을 생각하고 어떻게 풀어야할지를 고민해야했던 문제였다!
> PSG : [#158][#160][#161][#162] 순수연 - 코드를 꼼꼼하게 보고 짜기!

- Programmers/0625/[PGS] [1차] 추석 트래픽.py
- Programmers/0625/[PGS] 등굣길.py
- Programmers/0625/[PGS] 베스트앨범.py
- Programmers/0625/[PGS] 입국심사.py
- Simulation/[BOJ] 1713_후보 추천하기.py
- Simulation/[BOJ] 20436_ZOAC 3.py
- Simulation/[BOJ] 5212_지구 온난화.py
- String/[BOJ] 1213_팰린드롬 만들기.py
- String/[BOJ] 1764_듣보잡.py
- String/[BOJ] 19583_싸이버개강총회.py
- #175 
- #176 
- #178 
- #179
- #177 
- 딕셔너리에 대한 이해도
- 시뮬레이션(구현)을 하기 위한 수도 코드 작성하고 풀기
- 효율적인 코드 짜도록 노력하기
> BOJ : [#175][#176][#178][#179][#180] - 미리미리 문제 풀고 시간 맞추서 올리기..ㅠㅠ

- programmers/0703/ZOAC3.py
- programmers/0703/듣보잡.py
- programmers/0703/싸이버개강총회.py
- programmers/0703/지구온난화.py
- programmers/0703/팰린드롬만들기.py
- programmers/0703/후보추천하기.py
> BOJ [#175][#176][#177][#178][#179][#180] 유지원 - 구현에 대해서 dfs/bfs말고 다른 것도 생각해보기/set과 list 잘 활용하기

- Simulation/[BOJ] 14891_톱니바퀴.py
- Simulation/[BOJ] 20056_마법사 상어와 파이어볼.py
- String/[BOJ] 17609_회문.py
- String/[BOJ] 2671_잠수함식별.py
- #182 
- #183 
- #181 : 투 포인터 활용까지 알았는데 구현해내지못해 너무 아쉬운 문제였다.. 구현 문제를 많이 접해봐야겠다
- #184 : 문제 이해부터 실패한 문제..
- 문제 이해를 위해 문제를 보고 요약해보기 => 중요한 부분 체크
- 구현 연습하기
> BOJ : [#182][#183] 순수연 - 문제를 어떻게 빨리 이해할지 생각해보자!

- Random/0702/[백준] 14891_톱니바퀴.py
- Random/0702/[백준] 17609_회문.py
- Random/0702/[백준] 20056_마법사 상어와 파이어볼.py
- Random/0702/[백준] 잠수함식별.py
- #182 : 너무 복잡해보이고 정규식풀이로 풀어야 되는거 아닌가라는 생각이 강하게 들어서 포기했다 어떻게든 생각해보고 풀어볼걸 그랬다.
- #183 : 그냥 모든 경우를 if문으로 확인했다. 재귀로 풀어야한다는 생각이 들었는데 생각하고 싶지 않았던 것 같다. 앞으로는 도망치지 말자
-  #184 : 문제를 잘못읽어서 1시간은 문제만 봤던 것 같다. 쉬다가 다시 와서 봤더니 잘못 이해했다는 것을 알아채고 다음날 차근 차근 요구사항대로 풀었더니 풀렸다. 시뮬레이션은 복잡한 조건을 어떻게 잘 이해해서 구현을 하는지가 중요한 것 같다
> BOJ : [#181][#183][#184] 최재훈 - 문제를 꼼꼼하게 읽고 어떻게든 풀어보기

- BFS DFS/0706/[BOJ] 14716_현수막.py
- BFS DFS/0706/[BOJ] 2583_영역 구하기.py
- BFS DFS/0706/[BOJ] 2644_촌수계산 .py
- Backtracking/[BOJ] 1182_부분수열의 합.py
- Backtracking/[BOJ] 15649_N과 M (1).py
- Backtracking/[BOJ] 15663_N과 M (9).py
- [#195] : 조합으로 성공했는데 백트래킹으로는 처음에 헷갈려서 결국 다른 사람 풀이를 참고했다...
- [#196]
- [#197]
- [#198]
- [#199]
- [#200]
- 백트래킹 공부
- 한 문제로 BFS DFS 둘 다 풀어보는 습관을 가져야겠다.
> [BOJ] : [#195][#196][#197][#198][#199][#200] 순수연 - BFS DFS 둘 다 생각해보는 습관을 가지자!

- Random/0706/[백준] 1182_부분수열의 합.py
- Random/0706/[백준] 14716_현수막.py
- Random/0706/[백준] 15649_N과 M(1).py
- Random/0706/[백준] 15663_N과 M(9).py
- Random/0706/[백준] 2583_영역 구하기.py
- Random/0706/[백준] 2644_촌수계산.py
- #195 : 백트래킹을 잘 몰라서 답을 보고 익힌 뒤 n과 m 시리즈를 몇 개 풀어보았다 그랬더니 어느정도 백트래킹을 알게 된 것 같다
> BOJ : [#196][#197][#198][#199][#200] 최재훈 - 백트래킹 조금 알게 된 것 같다

- backtracking/README.md
- backtracking/백준_14712_넴모넴모-Easy.py
- backtracking/백준_18430_무기-공학.py
- graph_traversal/README.md
- graph_traversal/백준_2194_유닛-이동시키기.py
- graph_traversal/백준_5547_일루미네이션.py
- #201
도저히 풀이법을 몰라서 찾아봤지만, 차근차근 다시 이해해봐야겠다. 
코드 자체가 어렵다기 보다는 "백트래킹" 풀이법이 손에 익지 않았다..
- #202
다음 좌표를 어떻게 설정할지, 종료 조건을 어떻게 설정할지 모르겠다.
- #203
bfs로 탐색시에, 좌표 한개가 아닌 한 면을 탐색하는것을 어떻게 구현할지 꽤 고민했다.
4%에서 계속 틀리는데, 뭐가 문제인지 모르겠다. 상하좌우 탐색에서 틀린걸까? 아니면 이동 불가능한 경우를 제대로 처리하지 못한걸까?
재귀에 대한 이해가 부족해서, 매번 무한루프에 빠지곤 한다. 어떻게 하면 로직을 짤 때, 재귀에 들어갈 경우를 직관적으로 그려볼 수 있을까?
- #204
육각형이어도 일반적인 배열처럼 푼다는걸 기억하자.
그리고 건물에 둘러쌓인 빈 공간 같은 반례에서는 bfs를 빈 공간 탐색으로 해야한다는 것도 기억하자.
> BFS/DFS, Backtracking : [#204] 마주연 - 재귀를 더 이해하고 공부해야겠다

- BFS & DFS/0713/[백준] 16918_봄버맨.py
- BFS & DFS/0713/[백준] 2468_안전 영역.py
- BFS & DFS/0713/[백준] 5014_스타트링크.py
- Backtracking/0713/[백준] 10971_외판원 순회 2.py
- Backtracking/0713/[백준] 14888_연산자 끼워넣기.py
- Backtracking/0713/[백준] 6603_로또.py
- #212 : n과 m 시리즈 문제와 비슷했던 것 같다
- #213 : 이 문제를 풀면서 백트래킹 이해도가 좀 더 높아진 것 같다.
- #214 :  for문을 이용한 백트래킹만 풀어봐서 if문으로 나눠서 풀 생각을 못했다. 아이디어는 생각을 했지만 백트래킹 구현력이 부족하다. 그래도 어느정도 이해를 하고 있으니 다양한 문제를 접하면서 계속 공부해봐야겠다.
-  #215 : bfs는 잔실수가 많이 생길 수 있는 것 같다
-  #216 : 생각보다 까다로웠다. 좀더 단순하게 풀고 싶었지만 안돼서 그냥 풀었다.
-  #217 : 전에 풀어봤던 문제와 비슷해서 금방 풀었던 것 같다
> BOJ : [#212][#213][#215][#216][#217] - 최재훈 : 백트래킹 이해는 어느정도 됐고, 이제 다양한 문제를 풀어봐야겠다.

- BFS DFS/0709/[BOJ] 2194_유닛 이동시키기.py
- BFS DFS/0713/[BOJ] 16918_봄버맨.py
- BFS DFS/0713/[BOJ] 2468_안전 영역.py
- BFS DFS/0713/[BOJ] 5014_스타트링크.py
- Backtracking/0713/[BOJ] 10971_외판원 순회.py
- Backtracking/0713/[BOJ] 14888_연산자 끼워넣기.py
- Backtracking/0713/[BOJ] 6603_로또.py
- #212 : 두 갈래로 나뉘어지는 재귀들 공부하기
- #213 : 시간초과가 났었던 문제.. 배열을 다룰 때는 시간에 대해 많이 생각해보자!
- #214 : 많이 복잡하게 생각했던것같다..! 백트래킹 속에 숫자들도 함께 전달했으면 더 깔끔하게 풀 수 있었을 것 같다. int(숫자)도 기억해두기!
- #215 : dfs/bfs 둘 다 풀었는데 bfs가 훨씬 빨랐다
- #216 : 예전에 풀었던 문제인데 그 때는 못 풀었는데 지금은 풀 수 있어서 실력이 늘었구나 싶었던 문제였다.
- #217 : 이게 왜 그래프 문제일까 생각하다가 그래프를 그려보면서 생각해봤더니 풀 수 있었다. 안 풀린다고 쉽게 포기하지 말고 계속 생각해봐야겠다
- 코드를 효율적으로 짤 수 있도록 노력하자!
> BOJ : [#212][#213][#214][#215][#216][#217] - 순수연 : 효율적인 코드를 짜도록 더 노력하자

- BFS & DFS/0716/[백준] 2206_벽 부수고 이동하기.py
- BFS & DFS/0716/[백준] 5427_불.py
- Backtracking/0716/[백준] 1759_암호 만들기.py
- Backtracking/0716/[백준] 9663_N-Queen.py
- #218 : 백트래킹의 유명한 문제로 알고 있었는데 시간초과를 피할 수 없어서 너무 어려웠다. 시간초과를 피하려면 배열 삽입삭제가 아니라 방문처리를 통해 O(1)로 접근하는 게 좋다.  또 배열 인덱스를 이런식으로 활용할 줄 몰랐는데 좋은 경험이 되었다. 이제 백트래킹을 좀 안 것 같기는 한데 이 문제는 백트래킹이어서가 아니라 그냥 접근법이 어려웠던 문제같다. 처음 접하면 시간초과를 피하는게 힘들 것 같은 문제이다
- #219 : 백트래킹은 코드 모양이 다 비슷한 것 같다는 생각이 들었다.
- #220 : 좀 더 깔끔하게 풀고 싶다
- #221 : 이것은 골드3이긴한데 제출 수가 많아서 골랐다. 3중배열을 이용한 적이 전에 있던 것 같긴한데 이 문제는 3중배열을 통해 재귀의 느낌이라고 해야하나? 살짝 색다른 느낌의 bfs였다.
> BOJ : [219][220] - 최재훈 : 어려웠다

- BFS DFS/0720/[BOJ] 16973_직사각형 탈출.py
- BFS DFS/0720/[BOJ] 2573_빙산.py
- BFS DFS/0720/[BOJ] 7569_토마토.py
- BFS DFS/0720/[BOJ] 9466_텀 프로젝트.py
- README.md
- #227 : 범위가 적어서 그냥 편안하게 풀었다.
- #228, #229, #230 : 시간초과로 인해 풀지 못했다.
- 시간 복잡도를 잘 생각하면서 풀기
- 어떻게 하면 시간을 줄일 수 있을지 잘 생각해보기
- 늦게 올려서 죄송합니다..ㅠㅠ 좀 더 생각해보자하다가 시간이 오래 걸렸네요.. 앞으로 한시간 이상이면 그냥 참고보고 풀어야겠어요!
> BOJ : [227] 어떻게 하면 시간을 줄일 수 있을지 많이 생각해보기!

- BFS & DFS/0720/[백준] 16973_직사각형 탈출.py
- BFS & DFS/0720/[백준] 2573_빙산.py
- BFS & DFS/0720/[백준] 7569_토마토.py
- BFS & DFS/0720/[백준] 9466_텀 프로젝트.py
- #227 : z축만 만들면 일반 bfs와 똑같은 느낌이었다.
- #228 : 이전에 풀어봤던 문제와 비슷한데 좀 다른 방식으로 풀어보려 했던 이유 때문인지 시간 초과가 자꾸 났다. 효율적인 풀이를 염두에 두고 풀어야겠다.
- #229 : 빙하를 녹이고 갱신을 하면된다
- #230 : 시간초과를 피하기 힘들었다. 그래서 계속 시간을 줄일 방법을 생각하면서 통과시켰다.
시간복잡도를 대략적으로만 생각하고 푸는데 앞으로는 최대한 더 줄이면서 풀려고 노력해야겠다
> BOJ : [227][229][230] - 최재훈 : 티어가 올라갈수록 시간초과를 신경써서 풀어야함을 느낀다

- Backtracking/0723/[백준] 1062_가르침.py
- Backtracking/0723/[백준] 16987 - 계란으로 계란치기.py
- Backtracking/0723/[백준] 1941_소문난 칠공주.py
- Backtracking/0723/[백준] 2580 - 스도쿠.py
- #234 : 7명을 어떻게 붙어 있게 뽑을지 생각이 안나서 못풀었다. 그냥 무작위로 뽑은 후 붙어있는지 확인하는 것이었다...
- #231 : 어떻게 어떻게 풀긴했는데 어렵다
- #232 : 메모이제이션은 dp에서만 사용하는 줄 알았는데 백트래킹에서도 쓰였다. 메모이제이션은 이곳저곳에서 유용하게 쓸 수 있을 것 같다'
- #233 : 비트마스킹으로 풀어야한다는데 비트마스킹은 잘 모르겠다..
> BOJ : [231][232] - 최재훈 : 시간초과에 계속 당하다보니 완탐적인 풀이를 잘 못하게 되고 있다.

- backtracking/백준_14712_넴모넴모-Easy.py
- dynamic_programming/README.md
- dynamic_programming/백준_12865_평범한-배낭.py
- dynamic_programming/백준_1915_가장-큰-정사각형.py
- dynamic_programming/백준_2629_양팔저울.py
- dynamic_programming/백준_9084_동전.py
DP는 정말 점화식 세우는게 너무 어렵다. 반례를 빨리 찾고 문제를 빨리 해결하는게 매우 중요한 것 같다.
그리고.. 또 문제를 너무 붙잡았다. 골드는 정말.. 1시간 2시간이 그냥 흘러가버린다..
- #241
전에 백준에서 푼 문제와 같았는데, 좀 헤맸다..ㅎ
- #242
반례에서 막히는 바람에, 푸는데 매우 오래 걸렸다. 
- #243
성공하긴 했는데, 매우 느리고 DP로 풀지 않았다. 맞힌 사람 풀이를 보니 훨씬 간단하게 풀었더라.. 다시 풀어봐야겠다.
- #244
dp를 리스트로 해서 느린듯 하다. 딕셔너리로 해야겠다.
> DP : [#241][#242][#243][#244] 마주연 -  반례를 빨리 찾자. 풀이시간을 단축하자.

- dynamic_programming/README.md
- dynamic_programming/백준_1520_내리막-길.py
- dynamic_programming/백준_2225_합분해.py
- dynamic_programming/백준_2631_줄세우기.py
- dynamic_programming/백준_5557_1학년.py
전체적으로 점화식의 실마리도 잡지 못하고 헤매다가 실패했다. 아니 점화식 전에 dp 유형이라는게 감이 안 잡히기도 하다..
dp는 왜 풀어도 익숙해지지 않는걸까..
단순히 상하좌우의 값을 갱신하는 점화식을 세웠지만,미래, 즉 아직 탐색하지 않은 좌표의 값을 어떻게 갱신해야할지 모르겠다.
이게 왜 dp인지 모르겠다.. 아무리 생각해도 완전탙ㅁ색으로만 보인다.
탑다운인지, 바텀업으로 하는게 좋을지 감도 잡히지 않는다.
- #245
전깃줄 문제와 비슷한데, 최대 증가 수열의 길이를 구하는 문제였다.
> DP : [#245] 마주연 - 왜 dp 유형인지 파악도 안된다..

- DP/0726/[백준] 1915_가장 큰 정사각형.py
- DP/0726/[백준] 2629_양팔저울.py
- DP/0726/[백준] 9084_동전.py
원래 dp가 약한 편이긴 한데 오랜만에 해서인지 하나도 못풀었다..
알고보니 이번 문제들이 다 배낭 알고리즘 관련된 문제들이었는데 전에도 이것과 관련된 문제를 잘 못 풀었던 것 같다..
따로 dp를 풀어보면서 수련해야겠다..
하나도 못풀다니... 믿기지가 않는다..
> BOJ : 최재훈 - 꿈인가... 하나도 못풀다니..

- binary_search/백준_10816_숫자-카드-2.py
- binary_search/백준_1654_랜선자르기.py
- binary_search/백준_1920_수-찾기.py
- binary_search/백준_2805_나무자르기.py
- #270 , #273
기본적인 이분탐색 코드를 활용하여 원소의 개수를 세기 위한 bisect 라이브러리를 공부했다. 기본적인 이분탐색 코드와 갱신 코드가 달라서 직접 배열을 그려가면서 이해했다. 
#272 와 #273 두 문제 모두 "최대 얼마나 잘라야 하나"는 유형이었다. 이때 목표값과 일치해도 바로 return 하지 말고 계속 갱신해야 최댓값을 찾을 수 있다는 것이 포인트였다.
이분탐색은 기본 코드를 잘 응용하는게 포인트같다. 특히 mid 에 1을 더하거나 1을 빼면서 start와 end를 갱신 할 때, 조건을 잘 구분해서 설정해야겠다. 이때 인덱스 범위가 조금 헷갈리긴 하는데.. 헷갈릴 때는 예제를 적어가면서 풀어야겠다.
> [Binary Search] : [#270][#273] 마주연 - 기본 코드를 잘 응용하자

- Binary Search/0810/[백준] 10816_숫자 카드2.py
- Binary Search/0810/[백준] 1654_랜선 자르기.py
- Binary Search/0810/[백준] 1920_수 찾기.py
- Binary Search/0810/[백준] 2805_나무 자르기.py
- #270   #271 이 비슷한 느낌이고 #272 #273 이 비슷한 느낌이었다.
이분탐색의 개념을 알면 다 풀 수 있을 것 같다
이번주까지는 개인적인 사정 때문에 커멘트를 못달수도 있습니다. ㅠㅠ
> Binary Search : [#270][#271][#272][#273] 최재훈 - 개념을 알면 풀 수 있는 문제들이었다

- DP/0730/[BOJ] 1520_내리막 길.py
- DP/0730/[BOJ] 2225_합분해.py
- DP/0730/[BOJ] 2631_줄세우기.py
- DP/0730/[BOJ] 5557_1학년.py
- #245 : 가장 긴 증가하는 수열 찾기부분을 엄청 많이 봤는데 매번 못 풀었던 것 같다..ㅜㅜ.. 공부가 더 필요한 것 같다.
- #246 : dfs + dp를 섞어서 푸는 문제였는데 아직 알고리즘을 섞는것에서 부족한 것 같다.
- #247 : 왜 dp지....라고 생각했던 문제..ㅠ
- #248 : dp인데 사실 dp로 못풀었다.. (공식을 통한 풀이..) 근데 dp 풀이를 보니 너무 쉬워서 놀랐다...
- 목요일 풀이는 다 못 풀어서 공부해놓겠습니다.
- dp인데 지금은 dp문제를 풀어서 dp구나 하겠는데 유형을 모른채 만나면 dp라는 생각을 못할 것 같다.
- 이중배열을 사용하는 dp에 특히 더 약한 것 같다.
> BOJ : [#248] 순수연 - DP 공부하기..

- Binary Search/0817/[백준] 2343_기타 레슨.py
- Binary Search/0817/[백준] 2470_두 용액.py
- Binary Search/0817/[백준] 2792_보석 상자.py
- Binary Search/0817/[백준] 3020_개똥벌레.py
- #282 :  문제를 어떻게 풀어야 할 지는 알았는데 너무 복잡해질 것 같아서 그냥 답을 봤는데 나의 생각과 같았다. 그런데 내가 생가각하기에 애매한 부분을 그냥 고려하지 않고 그냥 구현해도 문제가 풀렸다... 그런데 왜 그런지 모르겠다.
- #284 : 뭐를 이분탐색 해야 할 지 감이 잡히지 않아서 못 풀었다. 지속적인 훈련이 필요한 듯 하다
- #285 : 투 포인터로 풀었다. 이분탐색보다는 투 포인터가 더 출제의도에 맞는 문제같지만 이분탐색의 새로운 방식을 생각해볼 수있었다.
> Binary Search : [#283][#285] 최재훈 - 이분탐색의 기준이 되는 것을 찾는 것이 중요

- Programmers/Programmers_Lv2/프로그래머스_12913_땅따먹기.py
- Programmers/Programmers_Lv2/프로그래머스_49993_스킬트리.py
- Programmers/Programmers_Lv3/README.md
- Programmers/Programmers_Lv3/프로그래머스_17678_1차-셔틀버스.py
- Programmers/Programmers_Lv3/프로그래머스_43163_단어 변환.py
- binary_search/백준_1477_휴게소-세우기.py
- binary_search/백준_2343_기타-레슨.py
- binary_search/백준_8983_사냥꾼.py
- #292
긴장한 탓인지 문제 이해와 구상에 오래걸렸다.
지저분하게나마 겨우 풀었다고 생각했지만, 반례에서 틀렸다. 반례가 뭘까..?
- 첫 문제가 너무 어려웠지만 끝까지 붙잡지 않고 다른 문제로 넘어간 후, 다 풀고 나서 다시 돌아온 덕분에 시간 안에 많은 문제를 풀 수 있었다. 스터디에서 캠을 켜고 시간을 제한하고 문제를 푸니, 확실히 조금이나마 실전 느낌이 났다. 긴장하니까 문제 이해가 느려지고, 문제 유형 파악이 쉽지 않았다. 앞으로도 실전 연습을 더 많이 하면서 시간 안에 문제를 이해하고 유형을 파악해서 침착하게 문제를 푸는 연습을 해야겠다.
- #294
DFS로 풀었지만, BFS로 다시 풀어봐야겠다.
또한 global, local, nonlocal에 대해 배웠으니 앞으로 중첩 함수에서 사용해야겠다.
- #293 dp, #295 구현
- #282
스터디때 다뤘지만, 반복문에서 start와 end 가 이상인지 초과인지, 조건문에서 갱신을 어떻게 나눌지 등에 따라 출력이 달라지는게 아직 잘 이해되지 않는다. 아무래도 이분탐색에 대한 이해를 더 해봐야겠다.
> PSG : [#293][#294][#295][#282] 마주연 - 시간안에 푸는 습관을 들이자

- BFS & DFS/0904/[프로그래머스] 단어 변환.py
빨리 구현해야겠다는 생각으로만 풀어서 코드가 난잡한데 이런느낌이 bfs구나라고만 생각해주시면 될 것 같습니다.
푸시하고 나서 보니 주석을 못달았다는 걸 알았는데 혹시 궁금한 점 있으시면 커멘트 달아주세요
> BFS : [#294] 최재훈 - 단어변환 bfs 풀이입니다.
